global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI application metrics
  - job_name: 'llm-rag-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Dagster metrics
  - job_name: 'dagster'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/dagster/metrics'
    scrape_interval: 30s

  # ChromaDB metrics (if available)
  - job_name: 'chromadb'
    static_configs:
      - targets: ['chroma:8000']
    metrics_path: '/api/v1/heartbeat'
    scrape_interval: 30s

  # System metrics via node_exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Pushgateway for batch jobs
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  # Telegram bot metrics
  - job_name: 'telegram-bot'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s